// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aczvhomywkoshbwbjivd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjenZob215d2tvc2hid2JqaXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MTQ4MjAsImV4cCI6MjA3ODE5MDgyMH0.Ys0OR6HFGLMMzbe8drXc0tz3hPrWFxHZDH44ExaH5Uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});